name: dispatched_calculator_app
description: "Cloud Fleet Calculator"
publish_to: "none" # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: ">=3.3.4 <4.0.0"
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  get: ^4.6.6
  velocity_x: ^4.2.1
  firebase_core: ^2.32.0
  firebase_auth: ^4.20.0
  cloud_firestore: ^4.17.5
  shimmer: ^3.0.0
  tutorial_coach_mark: ^1.2.11
  shared_preferences: ^2.2.3
  google_mobile_ads: ^5.1.0
  flick_video_player: ^0.8.0
  video_player: ^2.9.1
  android_alarm_manager_plus: ^4.0.3
  fl_chart: ^0.68.0
  syncfusion_flutter_charts: ^26.1.42
  package_info_plus: ^8.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
flutter:
  uses-material-design: true
  assets:
    - assets/images/
  fonts:
    - family: Raleway-Regular
      fonts:
        - asset: assets/fonts/Raleway-Regular.ttf
          weight: 600
    - family: Raleway-Bold
      fonts:
        - asset: assets/fonts/Raleway-Bold.ttf
          # - asset: fonts/TrajanPro_Bold.ttf
          weight: 700
    - family: Roboto-Regular
      fonts:
        - asset: assets/fonts/Roboto-Regular.ttf
          # - asset: fonts/TrajanPro_Bold.ttf
          weight: 700
