// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB5lHLGA8DxZ-b-WYmlNrHgnPgcWKqNs40',
    appId: '1:937943912549:web:0b6cf24a33855c5ad9b68c',
    messagingSenderId: '937943912549',
    projectId: 'dispatch-calculator-f7ad8',
    authDomain: 'dispatch-calculator-f7ad8.firebaseapp.com',
    storageBucket: 'dispatch-calculator-f7ad8.appspot.com',
    measurementId: 'G-6NNEZFXNET',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCKnLjO-GUDGXOQ4K7XmfaXpNurm4uPikY',
    appId: '1:937943912549:android:95e9a709498e06c2d9b68c',
    messagingSenderId: '937943912549',
    projectId: 'dispatch-calculator-f7ad8',
    storageBucket: 'dispatch-calculator-f7ad8.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBynT2jAvmeTOeQvEu5jIvK7SQjTR3Q1FY',
    appId: '1:937943912549:ios:c4159567d0668fd3d9b68c',
    messagingSenderId: '937943912549',
    projectId: 'dispatch-calculator-f7ad8',
    storageBucket: 'dispatch-calculator-f7ad8.appspot.com',
    iosBundleId: 'com.example.dispatchedCalculatorApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBynT2jAvmeTOeQvEu5jIvK7SQjTR3Q1FY',
    appId: '1:937943912549:ios:c4159567d0668fd3d9b68c',
    messagingSenderId: '937943912549',
    projectId: 'dispatch-calculator-f7ad8',
    storageBucket: 'dispatch-calculator-f7ad8.appspot.com',
    iosBundleId: 'com.example.dispatchedCalculatorApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB5lHLGA8DxZ-b-WYmlNrHgnPgcWKqNs40',
    appId: '1:937943912549:web:cdbd04615c49a34dd9b68c',
    messagingSenderId: '937943912549',
    projectId: 'dispatch-calculator-f7ad8',
    authDomain: 'dispatch-calculator-f7ad8.firebaseapp.com',
    storageBucket: 'dispatch-calculator-f7ad8.appspot.com',
    measurementId: 'G-4ZSBQ8SE9E',
  );
}
